### PR TITLE
Document try_enqueue implicit producer index limit (#418)

### LINKED ISSUE #418: When there is lot of enqueue , it fails
I have been using queue like this 

parallelQueue::ConcurrentQueue<myDS,mYTraits> *pMPSC_consume; 

pMPSC_consume = new ConcurrentQueue(PARALLEL_QUEUE_MAX_NODES, 0, enteredNoOfThreads);

and when i call pMPSC_consume->try_enqueue() , its failing at times .... 

I have given PARALLEL_QUEUE_MAX_NODES and even at times there are close to like max 10K to 20K in loop, but even then the try_enqueue fails , please let me know what i need to do to handle this 

thanks

### PR DESCRIPTION
**Pull request by PavelGuzenfeld**
## Summary
- Added documentation to `ConcurrentQueueDefaultTraits::IMPLICIT_INITIAL_INDEX_SIZE` explaining the relationship between `BLOCK_SIZE`, `IMPLICIT_INITIAL_INDEX_SIZE`, and the maximum elements per implicit producer when using `try_enqueue`
- Added clarifying note on the `try_enqueue` method that pre-allocating blocks via the constructor does not increase the block index size
- Added `implicit_producer_index_limit` unit test demonstrating the limit and both workarounds (use `enqueue()` or increase `IMPLICIT_INITIAL_INDEX_SIZE`)

## Test plan
- [x] Unit test `implicit_producer_index_limit` passes (8 iterations, all green)
- [x] Full test suite builds with gcc:14

Fixes #418

### CODE REVIEW

File: tests/unittests/unittests.cpp [hunk 1]
```diff
@@ -5031,6 +5044,68 @@ class ConcurrentQueueTests : public TestClass<ConcurrentQueueTests>
...
+				if (!q.try_enqueue(i))
+					break;
+				++successCount;
+			}
+			// try_enqueue should stop succeeding at the index limit
+			ASSERT_OR_FAIL(successCount == limit);
+		}
+
+		{
+			// Fix #1: enqueue() (which can allocate) works past the limit
```
Comment (cameron314) [inline tests/unittests/unittests.cpp]: To me, this comment reads as if this is testing a fix in the code, whereas it's actually demonstrating a workaround to the API behaving as designed.


```suggestion
			// Workaround #1: enqueue() (which can allocate) can grow the index
```

File: tests/unittests/unittests.cpp [hunk 2]
```diff
@@ -5031,6 +5044,68 @@ class ConcurrentQueueTests : public TestClass<ConcurrentQueueTests>
...
+			int item;
+			for (int i = 0; i < limit + 64; ++i) {
+				ASSERT_OR_FAIL(q.try_dequeue(item));
+				ASSERT_OR_FAIL(item == i);
+			}
+			ASSERT_OR_FAIL(!q.try_dequeue(item));
+		}
+
+		{
+			// Fix #2: larger IMPLICIT_INITIAL_INDEX_SIZE allows more try_enqueue calls
```
Comment (cameron314) [inline tests/unittests/unittests.cpp]:
```suggestion
			// Workaround #2: larger IMPLICIT_INITIAL_INDEX_SIZE allows more try_enqueue calls
```

File: concurrentqueue.h [hunk 3]
```diff
@@ -355,6 +355,12 @@ struct ConcurrentQueueDefaultTraits
 	
 	// How many full blocks can be expected for a single implicit producer? This should
 	// reflect that number's maximum for optimal performance. Must be a power of 2.
+	// Note: This controls the maximum number of elements that can be enqueued by a
+	// single implicit producer when using try_enqueue (which does not allocate).
+	// The limit is BLOCK_SIZE * IMPLICIT_INITIAL_INDEX_SIZE elements; beyond that,
+	// the block index needs to grow, which requires allocation, causing try_enqueue
+	// to fail. Increase this value (or use enqueue(), which can allocate) if you need
+	// more capacity per implicit producer. See also issue #418.
```
Comment (cameron314) [inline concurrentqueue.h]: This is one limiting factor, but not the only one (`BLOCK_SIZE` plays a role too, and the number of blocks preallocated, and it's possible to mix `try_enqueue` and `enqueue`).

I'm also not sure I like stating `BLOCK_SIZE * IMPLICIT_INITIAL_INDEX_SIZE elements`, since blocks are not necessarily full: if all blocks are filled up to this many elements, then one element is dequeued, a new element still can't be enqueued until the entire first block is emptied.

Also not sure I like referencing github issues in non-test code.

How about:

```suggestion
	// Note: This impacts the maximum number of elements that can be enqueued by a
	// single implicit producer when using try_enqueue/try_enqeue_bulk exclusively (which
	// cannot allocate), since it limits the number of blocks that the producer can hold to
	// store elements. When pre-allocating blocks for use with try-enqueueing, configure
	// this initial size to the desired maximum number of blocks per implicit producer.
	// Alternately, use the regular enqueue methods, which can grow the index as needed.
```

File: blockingconcurrentqueue.h [hunk 4]
```diff
@@ -56,18 +56,18 @@ class BlockingConcurrentQueue
 	// includes making the memory effects of construction visible, possibly with a
 	// memory barrier).
 	explicit BlockingConcurrentQueue(size_t capacity = 6 * BLOCK_SIZE)
-		: inner(capacity), sema(create<LightweightSemaphore, ssize_t, int>(0, (int)Traits::MAX_SEMA_SPINS), &BlockingConcurrentQueue::template destroy<LightweightSemaphore>)
+		: inner(capacity), sema(create<LightweightSemaphore, ssize_t, int>(0, static_cast<int>(Traits::MAX_SEMA_SPINS)), &BlockingConcurrentQueue::template destroy<LightweightSemaphore>)
```
Comment (cameron314) [inline blockingconcurrentqueue.h:59]: These casts were also introduced in a separate PR and now conflict with `master`.

File: concurrentqueue.h [hunk 5]
```diff
@@ -1056,6 +1069,11 @@ class ConcurrentQueue
 	// Does not allocate memory. Fails if not enough room to enqueue (or implicit
 	// production is disabled because Traits::INITIAL_IMPLICIT_PRODUCER_HASH_SIZE
 	// is 0).
+	// Note: For implicit producers (no token), the maximum number of elements that
+	// can be held is BLOCK_SIZE * IMPLICIT_INITIAL_INDEX_SIZE before the block
+	// index must grow (which requires allocation and causes try_enqueue to fail).
+	// Pre-allocating blocks via the constructor does not increase the index size.
+	// Increase IMPLICIT_INITIAL_INDEX_SIZE in your traits, or use enqueue() instead.
```
Comment (cameron314) [inline concurrentqueue.h]: This method does not accept a token, so it is implicit by definition.

Given the thorough note in the trait docs, I think it's fine to leave a shorter comment here referencing the traits.

```suggestion
	// Note: If using only try_enqueue/try_enqueue_bulk with pre-allocated blocks, configure
	// Traits::IMPLICIT_INITIAL_INDEX_SIZE appropriately to ensure the index has sufficient
	// capacity for the number of blocks each producer may need.
```

There are also other implicit try-enqueueing methods to which this note would equally apply. It should appear consistently on each.

**Review by cameron314 — CHANGES_REQUESTED** [review]
Thanks for opening this PR. This is definitely a gotcha that's bitten quite a few people over the years and improving the documentation around it is definitely worth doing.

**Review by PavelGuzenfeld — COMMENTED** [review]
Applied all suggested changes and rebased on master.

**Review by cameron314 — APPROVED** [review]
LGTM, thanks!
